import * as THREE from 'three';
import type { Engine } from '../engine';
import { ROOM_SPEC } from './scene';

export class RoomOrbit {
  private yaw = 0; private pitch = .5; private distance = 3.45; private yawVelocity = 0; private pitchVelocity = 0; private target = new THREE.Vector3(0, 1.18, 0); private pointers = new Map<number, { x: number; y: number; t: number }>(); private lastTap = 0; private easing = false;
  constructor(private engine: Engine, private canvas: HTMLCanvasElement) { window.addEventListener('pointerdown', this.down, true); window.addEventListener('pointermove', this.move, true); window.addEventListener('pointerup', this.up, true); window.addEventListener('pointercancel', this.up, true); window.addEventListener('wheel', this.wheel, { passive: false }); }
  private down = (e: PointerEvent) => { const pet = this.engine.hitTest(e.clientX, e.clientY); if (!pet && !this.engine.claimGesture(e.pointerId)) return; if (pet) { const now = performance.now(); if (now - this.lastTap < 320) this.focus(); this.lastTap = now; return; } this.pointers.set(e.pointerId, { x: e.clientX, y: e.clientY, t: performance.now() }); this.easing = false; };
  private move = (e: PointerEvent) => { const p = this.pointers.get(e.pointerId); if (!p) return; const now = performance.now(), elapsed = Math.max(8, now - p.t) / 1000; const dx = e.clientX - p.x, dy = e.clientY - p.y; const boost = THREE.MathUtils.clamp(1 + Math.hypot(dx, dy) / 130, 1, 1.3); const yawStep = -dx * .003 * boost, pitchStep = -dy * .0025 * boost; p.x = e.clientX; p.y = e.clientY; p.t = now; this.yaw += yawStep; this.pitch = THREE.MathUtils.clamp(this.pitch + pitchStep, .05, .7); this.yawVelocity = THREE.MathUtils.clamp(this.yawVelocity * .38 + yawStep / elapsed * .62, -1.35, 1.35); this.pitchVelocity = THREE.MathUtils.clamp(this.pitchVelocity * .38 + pitchStep / elapsed * .62, -1.1, 1.1); };
  private up = (e: PointerEvent) => { this.pointers.delete(e.pointerId); this.engine.releaseGesture(e.pointerId); };
  private wheel = (e: WheelEvent) => { e.preventDefault(); this.distance = THREE.MathUtils.clamp(this.distance + e.deltaY * .004, 2.8, 3.8); };
  focus() { this.target.set(0, 1.18, 0); this.distance = 3.2; this.easing = true; }
  update(dt: number) { if (this.easing) { this.distance += (3.2 - this.distance) * Math.min(1, dt * 8); if (Math.abs(this.distance - 3.2) < .01) this.easing = false; } const speed = Math.hypot(this.yawVelocity, this.pitchVelocity); this.yaw += this.yawVelocity * dt; this.pitch = THREE.MathUtils.clamp(this.pitch + this.pitchVelocity * dt, .05, .7); const damping = Math.exp(-(4.8 + Math.min(4, speed * 1.5)) * dt); this.yawVelocity *= damping; this.pitchVelocity *= damping; const c = this.engine.cameraRef; const room = ROOM_SPEC.room, clearance = ROOM_SPEC.clearance; const y = THREE.MathUtils.clamp(1.18 + Math.sin(this.pitch) * this.distance, clearance.cameraFloor, room.height - clearance.cameraCeiling); const r = Math.cos(this.pitch) * this.distance; const x = THREE.MathUtils.clamp(Math.sin(this.yaw) * r, -room.width / 2 + clearance.cameraWall, room.width / 2 - clearance.cameraWall); const z = THREE.MathUtils.clamp(Math.cos(this.yaw) * r, -room.depth / 2 + clearance.cameraWall, room.depth / 2 - clearance.cameraWall); c.position.set(x, y, z); c.lookAt(this.target.set(0, 1.18, 0)); c.fov = 52; c.updateProjectionMatrix(); }
  resize(w: number, h: number) { this.engine.cameraRef.aspect = w / h; this.engine.cameraRef.updateProjectionMatrix(); }
  dispose() { window.removeEventListener('pointerdown', this.down, true); window.removeEventListener('pointermove', this.move, true); window.removeEventListener('pointerup', this.up, true); window.removeEventListener('pointercancel', this.up, true); window.removeEventListener('wheel', this.wheel); for (const id of this.pointers.keys()) this.engine.releaseGesture(id); this.pointers.clear(); }
}
