import * as THREE from 'three';

export const ROOM_TOKENS = { floor: 0x9b7659, wall: 0xe9e0d2, trim: 0xc6a47d, rug: 0x7d9b94, bed: 0x75929a, fabric: 0xd7ded1, wood: 0x704b35, green: 0x5f805c, brass: 0xc79a53, light: 0xffe7b3 };
const ROOM = { width: 8, depth: 6, height: 3.2 };
const mat = (color: number, roughness = .86) => new THREE.MeshStandardMaterial({ color, roughness, metalness: 0 });
function box(scene: THREE.Scene, size: [number, number, number], position: [number, number, number], color: number, name: string, material: THREE.Material = mat(color)) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(...size), material); mesh.position.set(...position); mesh.name = name; scene.add(mesh); return mesh; }
function cylinder(scene: THREE.Scene, radius: number, height: number, position: [number, number, number], color: number, name: string, segments = 32) { const mesh = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius, height, segments), mat(color)); mesh.position.set(...position); mesh.name = name; scene.add(mesh); return mesh; }

function floorTexture() { const canvas = document.createElement('canvas'); canvas.width = canvas.height = 512; const x = canvas.getContext('2d')!; x.fillStyle = '#9b7659'; x.fillRect(0, 0, 512, 512); for (let y = 0; y < 512; y += 42) { x.fillStyle = y % 84 ? '#a47d5e' : '#927052'; x.fillRect(0, y, 512, 40); x.strokeStyle = 'rgba(55,32,18,.18)'; x.beginPath(); x.moveTo(0, y + 40); x.lineTo(512, y + 40); x.stroke(); for (let seam = (y / 42 % 2) * 90; seam < 512; seam += 180) { x.beginPath(); x.moveTo(seam, y); x.lineTo(seam, y + 40); x.stroke(); } } const texture = new THREE.CanvasTexture(canvas); texture.wrapS = texture.wrapT = THREE.RepeatWrapping; texture.repeat.set(1.2, 1); return texture; }
function fabricTexture(color: string, accent: string) { const canvas = document.createElement('canvas'); canvas.width = canvas.height = 128; const x = canvas.getContext('2d')!; x.fillStyle = color; x.fillRect(0, 0, 128, 128); x.strokeStyle = accent; x.globalAlpha = .2; for (let i = -128; i < 256; i += 16) { x.beginPath(); x.moveTo(i, 0); x.lineTo(i + 128, 128); x.stroke(); } return new THREE.CanvasTexture(canvas); }
function addWindow(scene: THREE.Scene) { const glass = new THREE.MeshBasicMaterial({ color: 0x9fc5cf, transparent: true, opacity: .72 }); box(scene, [2.15, 1.35, .04], [0, 1.9, -2.94], 0, 'window-glass', glass); box(scene, [2.35, .09, .1], [0, 2.6, -2.88], ROOM_TOKENS.trim, 'window-top'); box(scene, [2.35, .09, .1], [0, 1.2, -2.88], ROOM_TOKENS.trim, 'window-sill'); box(scene, [.1, 1.5, .1], [-1.12, 1.9, -2.88], ROOM_TOKENS.trim, 'window-frame'); box(scene, [.1, 1.5, .1], [1.12, 1.9, -2.88], ROOM_TOKENS.trim, 'window-frame'); box(scene, [.07, 1.35, .07], [0, 1.9, -2.87], ROOM_TOKENS.trim, 'window-mullion'); box(scene, [2.1, .06, .08], [0, 1.9, -2.86], ROOM_TOKENS.trim, 'window-mullion'); box(scene, [.2, 1.6, .05], [-1.28, 1.9, -2.84], 0xdcb5a0, 'curtain-left'); box(scene, [.2, 1.6, .05], [1.28, 1.9, -2.84], 0xdcb5a0, 'curtain-right'); }
function addPlant(scene: THREE.Scene, x: number, z: number) { cylinder(scene, .3, .35, [x, .18, z], 0xc17b55, 'plant-pot'); for (const [dx, dy, dz, scale] of [[-.22, .62, 0, .55], [.2, .72, .05, .62], [0, .92, -.05, .5], [.34, .55, -.08, .42]] as const) { const leaf = new THREE.Mesh(new THREE.SphereGeometry(.35, 16, 10), mat(ROOM_TOKENS.green)); leaf.scale.set(scale, 1.5 * scale, .35 * scale); leaf.position.set(x + dx, dy, z + dz); leaf.rotation.z = dx * 1.5; scene.add(leaf); } }
function addLamp(scene: THREE.Scene) { cylinder(scene, .035, 1.25, [2.72, .68, .2], ROOM_TOKENS.brass, 'lamp-stem'); cylinder(scene, .28, .12, [2.72, .05, .2], ROOM_TOKENS.brass, 'lamp-base'); const shade = new THREE.Mesh(new THREE.ConeGeometry(.32, .3, 24, 1, true), mat(0xe8c68f)); shade.position.set(2.72, 1.38, .2); scene.add(shade); const light = new THREE.PointLight(0xffd28a, 2.1, 5); light.position.set(2.72, 1.3, .2); scene.add(light); }
function addFeedingStation(scene: THREE.Scene) { const metal = new THREE.MeshStandardMaterial({ color: 0xb8c2c2, roughness: .25, metalness: .82 }); const bowl = new THREE.Mesh(new THREE.CylinderGeometry(.31, .24, .12, 32, 1, true), metal); bowl.position.set(2.2, .1, -1.75); bowl.name = 'metal-dog-feeder'; scene.add(bowl); const waterBase = new THREE.Mesh(new THREE.CylinderGeometry(.28, .3, .12, 24), metal); waterBase.position.set(2.85, .06, -1.75); waterBase.name = 'water-dispenser-base'; scene.add(waterBase); const bottle = new THREE.Mesh(new THREE.CylinderGeometry(.16, .2, .65, 24), new THREE.MeshStandardMaterial({ color: 0x8fc2c8, transparent: true, opacity: .72, roughness: .15, metalness: .1 })); bottle.position.set(2.85, .42, -1.75); bottle.name = 'water-dispenser'; scene.add(bottle); }
function addCouch(scene: THREE.Scene) { const fabric = new THREE.MeshStandardMaterial({ map: fabricTexture('#8b756b', '#c9b3a4'), roughness: 1 }); box(scene, [1.9, .35, .82], [2.75, .32, .72], 0, 'couch-seat', fabric); box(scene, [1.9, 1.05, .22], [2.75, .78, 1.02], 0, 'couch-back', fabric); box(scene, [.22, .62, .9], [1.85, .56, .72], 0, 'couch-arm-left', fabric); box(scene, [.22, .62, .9], [3.65, .56, .72], 0, 'couch-arm-right', fabric); box(scene, [.52, .13, .48], [2.25, .57, .52], 0, 'couch-cushion', new THREE.MeshStandardMaterial({ color: 0xb19d8c, roughness: 1 })); box(scene, [.52, .13, .48], [3.05, .57, .52], 0, 'couch-cushion', new THREE.MeshStandardMaterial({ color: 0xb19d8c, roughness: 1 })); box(scene, [.75, .12, .5], [1.38, .5, .7], ROOM_TOKENS.wood, 'couch-side-table'); cylinder(scene, .06, .48, [1.38, .74, .7], ROOM_TOKENS.brass, 'table-leg'); }
function addStairs(scene: THREE.Scene) { const dark = new THREE.MeshStandardMaterial({ color: 0x27383a, roughness: 1 }); box(scene, [1.2, 2.2, .08], [-3.32, 1.72, -2.91], 0, 'upstairs-fade', dark); for (let i = 0; i < 5; i++) box(scene, [1.35, .16 + i * .04, .48], [-3.1, .08 + i * .1, -1.05 - i * .37], ROOM_TOKENS.wood, 'stair-step'); const haze = new THREE.Mesh(new THREE.PlaneGeometry(1.05, 1.8), new THREE.MeshBasicMaterial({ color: 0xb5c7b0, transparent: true, opacity: .13, side: THREE.DoubleSide })); haze.position.set(-3.32, 1.65, -2.84); scene.add(haze); }
function addPainting(scene: THREE.Scene, x: number, y: number, z: number, color: number, side = false) { const frame = side ? [0.08, .85, 1.15] as [number, number, number] : [1.25, .85, .08] as [number, number, number]; const canvas = side ? [.04, .68, .98] as [number, number, number] : [1.04, .68, .04] as [number, number, number]; box(scene, frame, [x, y, z], ROOM_TOKENS.wood, 'painting-frame'); box(scene, canvas, [x + (side ? -.045 : 0), y, z + (side ? 0 : .045)], color, 'painting'); }
function addTV(scene: THREE.Scene) { box(scene, [.08, 1.15, 2.05], [3.91, 1.82, -1.1], 0x182329, 'wall-mounted-tv'); box(scene, [.04, .95, 1.82], [3.855, 1.82, -1.1], 0x3d6871, 'tv-screen'); box(scene, [.7, .06, .08], [3.82, 1.18, -1.1], 0x1a2629, 'tv-console'); }
function addFloorToys(scene: THREE.Scene) { cylinder(scene, .13, .08, [.85, .08, 1.25], 0xd25e54, 'floor-toy-ball'); cylinder(scene, .09, .09, [-.72, .09, -.72], 0xe0b34f, 'floor-toy-ball'); const bone = box(scene, [.62, .1, .17], [1.15, .09, .55], 0xe6d5b4, 'floor-toy-bone'); bone.rotation.y = -.35; }

export interface RoomScene { scene: THREE.Scene; update(dt: number): void; dispose(): void; }
export function createRoomScene(low = false): RoomScene {
  const scene = new THREE.Scene();
  const floor = new THREE.Mesh(new THREE.BoxGeometry(ROOM.width, .14, ROOM.depth), new THREE.MeshStandardMaterial({ map: floorTexture(), roughness: 1 })); floor.position.y = -.07; floor.name = 'room-floor'; scene.add(floor);
  box(scene, [ROOM.width, ROOM.height, .14], [0, ROOM.height / 2, -ROOM.depth / 2], ROOM_TOKENS.wall, 'back-wall'); box(scene, [.14, ROOM.height, ROOM.depth], [-ROOM.width / 2, ROOM.height / 2, 0], ROOM_TOKENS.wall, 'left-wall'); box(scene, [.14, ROOM.height, ROOM.depth], [ROOM.width / 2, ROOM.height / 2, 0], ROOM_TOKENS.wall, 'right-wall');
  box(scene, [ROOM.width, .12, .16], [0, .08, -ROOM.depth / 2 + .1], ROOM_TOKENS.trim, 'back-baseboard'); box(scene, [.16, .12, ROOM.depth], [-ROOM.width / 2 + .1, .08, 0], ROOM_TOKENS.trim, 'left-baseboard'); box(scene, [.16, .12, ROOM.depth], [ROOM.width / 2 - .1, .08, 0], ROOM_TOKENS.trim, 'right-baseboard');
  box(scene, [ROOM.width, .08, ROOM.depth], [0, ROOM.height + .02, 0], 0xd6c8b8, 'ceiling');
  const rugMat = new THREE.MeshStandardMaterial({ map: fabricTexture('#7d9b94', '#d7ded1'), roughness: 1 }); const rug = new THREE.Mesh(new THREE.BoxGeometry(5.1, .025, 3.45), rugMat); rug.position.set(-.15, .02, .45); rug.rotation.y = -.03; rug.name = 'open-play-mat'; scene.add(rug);
  box(scene, [1.65, .22, 1.12], [-2.05, .13, -1.2], ROOM_TOKENS.bed, 'dog-bed', new THREE.MeshStandardMaterial({ map: fabricTexture('#75929a', '#d7ded1'), roughness: 1 })); const pillow = new THREE.Mesh(new THREE.SphereGeometry(.4, 20, 12), mat(ROOM_TOKENS.fabric)); pillow.scale.set(1.45, .3, .8); pillow.position.set(-2.05, .32, -1.2); scene.add(pillow);
  addFeedingStation(scene);
  box(scene, [.68, .52, .5], [-2.7, .26, .95], ROOM_TOKENS.wood, 'toy-bin'); cylinder(scene, .11, .07, [-2.7, .57, .95], 0xd25e54, 'ball');
  if (!low) { addWindow(scene); addPlant(scene, 2.72, .95); addLamp(scene); addCouch(scene); addStairs(scene); addPainting(scene, -1.1, 2.1, -2.88, 0xc88367); addPainting(scene, 1.3, 2.1, -2.88, 0x7da4a5); addPainting(scene, -3.91, 2.12, .1, 0xc99d5a, true); addTV(scene); addFloorToys(scene); box(scene, [1.55, .7, .45], [.05, .35, -2.55], ROOM_TOKENS.wood, 'low-console'); for (let i = 0; i < 3; i++) box(scene, [1.25, .07, .12], [.05, .7 + i * .28, -2.55], ROOM_TOKENS.trim, 'console-shelf'); }
  const hemi = new THREE.HemisphereLight(0xfff4dd, 0x536a68, 2); scene.add(hemi); const key = new THREE.DirectionalLight(0xffd8a8, 2.7); key.position.set(-3, 5, 2); scene.add(key);
  return { scene, update: (_dt: number) => {}, dispose: () => { scene.traverse((o) => { const m = o as THREE.Mesh; if (m.geometry) m.geometry.dispose(); if (Array.isArray(m.material)) m.material.forEach((x) => x.dispose()); else if (m.material) m.material.dispose(); }); } };
}
