import { Engine } from '../engine';
import { RoomView } from './room/room';
import { loadPetSession, snapshotEngine } from './session';
import type { PlayContext, PlayView, PlayViewId, PetSession } from './types';

class CameraPlaceholder implements PlayView { readonly id = 'camera' as const; private ctx?: PlayContext; private ui?: HTMLElement; async enter(ctx: PlayContext) { this.ctx = ctx; ctx.engine.setView('camera', { petScale: .45 }); ctx.engine.setExternalCamera(true); ctx.engine.setOverlayScene(null); ctx.engine.setFurnitureSpots([]); ctx.engine.setSplatDepthTest(false); const ui = this.ui = document.createElement('div'); ui.className = 'camera-placeholder'; ui.innerHTML = `<div><span class="camera-placeholder-icon">◎</span><h1>Camera view is ready for the camera layer</h1><p>The shared Play shell and pet session are connected. Camera permissions, gyro anchoring and capture land in Part B.</p><button data-back>Back to room</button></div>`; ctx.root.appendChild(ui); ui.querySelector('[data-back]')?.addEventListener('click', () => ctx.switchTo('room')); } update(_dt: number) {} resize(_w: number, _h: number) {} exit() { this.ui?.remove(); this.ui = undefined; } }

export class PlayShell {
  readonly engine: Engine; readonly session: PetSession; private views = new Map<PlayViewId, PlayView>(); private current?: PlayView; private last = 0; private raf = 0; private root: HTMLElement; private canvas: HTMLCanvasElement; private peek: HTMLCanvasElement;
  private constructor(engine: Engine, session: PetSession, root: HTMLElement, canvas: HTMLCanvasElement, peek: HTMLCanvasElement) { this.engine = engine; this.session = session; this.root = root; this.canvas = canvas; this.peek = peek; this.views.set('room', new RoomView()); this.views.set('camera', new CameraPlaceholder()); }
  static async start() { const root = document.getElementById('play-root')!; const canvas = document.getElementById('play-canvas') as HTMLCanvasElement; const peek = document.getElementById('play-peek') as HTMLCanvasElement; const params = new URLSearchParams(location.search); const { session, fallback } = await loadPetSession(params.get('pet') ?? undefined); const shell = new PlayShell(new Engine(), session, root, canvas, peek); shell.engine.mount(canvas, peek); await shell.engine.loadPet(session.bundle); if (fallback) shell.notice('Using Pip, the placeholder dog — this pet bundle was unavailable.'); await shell.switchTo('room'); shell.loop(); return shell; }
  private context(): PlayContext { return { engine: this.engine, session: this.session, root: this.root, canvas: this.canvas, switchTo: (view) => void this.switchTo(view), exit: () => { location.href = `/`; } }; }
  async switchTo(id: PlayViewId) { if (this.current?.id === id) return; const next = this.views.get(id)!; const from = this.current?.id; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; this.root.classList.add('play-transition'); if (!reduced) await new Promise(resolve => setTimeout(resolve, 250)); if (this.current) { const state = snapshotEngine(this.session, this.engine); this.session.position = state.position; this.session.heading = state.heading; await this.current.exit(); } this.current = next; this.session.lastView = id; await next.enter(this.context(), from); if (!reduced) await new Promise(resolve => setTimeout(resolve, 250)); this.root.classList.remove('play-transition'); }
  private frame = (time = 0) => { const dt = Math.min(.1, this.last ? time - this.last : .016); this.last = time; this.current?.update(dt); this.current?.resize(innerWidth, innerHeight); this.raf = requestAnimationFrame(this.frame); };
  private notice(text: string) { const n = document.createElement('div'); n.className = 'play-notice'; n.textContent = text; this.root.appendChild(n); window.setTimeout(() => n.remove(), 4200); }
  loop() { this.raf = requestAnimationFrame(this.frame); }
  dispose() { cancelAnimationFrame(this.raf); void this.current?.exit(); this.engine.dispose(); }
}
